spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tbs_schema
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=TBSDB;
    # url: jdbc:sqlserver://172.20.16.1:1433;encrypt=true;trustServerCertificate=true;databaseName=E727DB;
    username: user
    password: password
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  application:
      name: tbs-api
server:
  port: '8080'
