spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=TBSDB;
    # PLEASE DO NOT CHANGE THE USERNAME AND PASSWORD
    username: user
    password: password
  #datasource:
  # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # url: jdbc:sqlserver://ec2-54-179-224-171.ap-southeast-1.compute.amazonaws.com:1433;encrypt=true;trustServerCertificate=true;databaseName=TBSDB;
  # username: sa
  # password: Password1234!
  sql:
    init:
      data-locations: classpath:data.sql
#      mode: always
  #  jpa:
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    generate-ddl: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  application:
    name: tbs-api
#  connect to aws rabbitmq
#  rabbitmq:
#    addresses: amqps://b-05a7bd65-7897-40d6-839a-2901f99cf5e2.mq.ap-southeast-1.amazonaws.com:5671
#    host: amqps://b-05a7bd65-7897-40d6-839a-2901f99cf5e2.mq.ap-southeast-1.amazonaws.com
#    port: 5671
#    username: admin
#    password: test@RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

    queue:
      name: ticketqueue
      exchange: ticketexchange
      routing:
        key: routingkey
server:
  port: "8081"

