spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=TBSDB;
    username: user
    password: password
  #datasource:
  # driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # url: jdbc:sqlserver://ec2-54-179-224-171.ap-southeast-1.compute.amazonaws.com:1433;encrypt=true;trustServerCertificate=true;databaseName=TBSDB;
  # username: sa
  # password: Password1234!
  sql:
    init:
      data-locations: classpath:data.sql
  #  jpa:
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    generate-ddl: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2019Dialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: true
  application:
    name: tbs-api
server:
  port: "8080"
